### ISSUE TITLE
knit problems new r 

### ISSUE THREAD

**Issue by Ribbontree** [maelle/rmd-blogging-course#3]
so error message

processing file: index.Rmd
  |......................................................................| 100%
  ordinary text without R code

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS index.utf8.md --to markdown_strict+pipe_tables+strikeout+autolink_bare_uris+task_lists+backtick_code_blocks+definition_lists+footnotes+smart+tex_math_dollars+native_divs+emoji --from markdown+autolink_bare_uris+tex_math_single_backslash+emoji --output index.md --wrap=none 
output file: index.knit.md

pandoc.exe: Unknown extension: task_lists
Fehler: pandoc document conversion failed with error 9
Ausführung angehalten

**Comment by maelle** [comment]
```r
getOption("pandoc.stack.size")
```

**Comment by maelle** [comment]
(Writing down what we discussed in Zoom) Sorry the main problem is probably " Unknown extension: task_lists" which means there's an issue with the Pandoc installation :grimacing:

**Comment by Ribbontree** [comment]
So I deinstalled and installed pandoc multiple times and restarted everything and now it works =)

**Comment by maelle** [comment]
MULTIPLE TIMES wow :sob: But I'm super happy to hear it works now! :tada:

**Comment by Ribbontree** [comment]
Yes, but thank you so much for your patient help!
